spring:
  datasource:
    url: ${LOADTEST_DB_URL:${LOCAL_DB_URL:${DB_URL:jdbc:mysql://localhost:3306/learning_loadtest?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true}}}
    username: ${LOADTEST_DB_USERNAME:${LOCAL_DB_USERNAME:${DB_USERNAME:root}}}
    password: ${LOADTEST_DB_PASSWORD:${LOCAL_DB_PASSWORD:${DB_PASSWORD:root}}}
    hikari:
      maximum-pool-size: ${LOADTEST_DB_HIKARI_MAXIMUM_POOL_SIZE:60}
      minimum-idle: ${LOADTEST_DB_HIKARI_MINIMUM_IDLE:10}

  jpa:
    hibernate:
      ddl-auto: update
